spring:

  application:
    name: @name@

  datasource:
    url: jdbc:h2:mem:waesdb
    username: sa
    password: victor@waes.in.2020
    driverClassName: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true

  jackson:
    default-property-inclusion: non_null
